databases:
  - name: learning-academy-db
    databaseName: learning_academy
    user: learning_academy_user

services:
  - type: web
    name: learning-academy
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn project.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning-academy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "learning-academy.onrender.com"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: PAYMENT_SUCCESS_URL
        value: "https://learning-academy.onrender.com/payments/success/"
      - key: PAYMENT_CANCEL_URL
        value: "https://learning-academy.onrender.com/payments/cancel/"
