# Generated by Django 5.2.4 on 2025-08-04 13:12

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_preview',
            field=models.FileField(blank=True, storage=storages.backends.s3.S3Storage(), upload_to='courses/previews/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='courses/videos/'),
        ),
    ]
